name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: faq
    attributes:
      label: FAQ
      description: Please check the [FAQ](https://kvan7.github.io/Exiled-Exchange-2/faq) before submitting an issue
      options:
        - label: I have checked the [FAQ](https://kvan7.github.io/Exiled-Exchange-2/faq) and my problem was not there
          required: true
  - type: checkboxes
    id: common-issues
    attributes:
      label: Common Issues
      description: Please check the [Common Issues Page](https://kvan7.github.io/Exiled-Exchange-2/issues) before submitting an issue
      options:
        - label: I have checked the [Common Issues Page](https://kvan7.github.io/Exiled-Exchange-2/issues) and my problem was not there
          required: true
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please check the [pinned issues and existing issues](https://github.com/Kvan7/Exiled-Exchange-2/issues?q=is%3Aissue) before submitting an issue
      options:
        - label: I have checked the [pinned issues and existing issues](https://github.com/Kvan7/Exiled-Exchange-2/issues?q=is%3Aissue) and my problem was not there
          required: true
  - type: dropdown
    id: common-bug
    attributes:
      label: Common Bugs
      description: Selection for bugs that are known to occur frequently with game updates
      options:
        - An error occurred while parsing the item
        - Not Recognized Modifier
        - No modifiers found
        - Other
      default: 3
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Change this text please"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of EE2 are you running? You can see this in Settings -> About
      options:
        - 0.13.9
        - 0.13.8
        - 0.13.7
        - 0.13.6
        - 0.13.5
        - 0.13.4
        - 0.13.3
        - 0.13.2
        - 0.13.1
        - 0.13.0
        - 0.12.x
        - 0.11.x
        - 0.10.x
        - Change me
      default: 13
    validations:
      required: true
  - type: textarea
    id: item
    attributes:
      label: Item Copy text
      description: PLEASE copy the item's text and paste it here. You can do so with `ctrl + alt + c` when hovering over the item, if your bug doesn't related to any items at all, write "None" (if it is about an item in any way and you write None it will be ignored)
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please go to Settings -> Debug, and copy and paste what is in that text box. (No need for backticks)
      render: shell
    validations:
      required: true
